### ISSUE TITLE
Main: Modifications to the output

### ISSUE THREAD

**Issue by egorananyev** [PK-HQ/fc#2]
1. Threshold data should go into 'data/thresh/' directory and adhere to the following naming convention: "FC_thresh_sub01_20160829_1758.csv".
2. Please record the eye dominance and the threshold used (high- and low-start staircase values, as well as the average used) either in the output file along with the rest of the session data. Those should be columns with a single value in them, like the subject ID. Please see the files for subjects 1 and 2 for example.

**Comment by egorananyev** [comment]
Please make sure that both of the following errors are fixed in the Matlab output:
1. Trial_number now reflects the trial order (was identical to Sentence_ID previously).
2. SubID was for some reason zero and another number (0 and 51 for subject 3; 0 and 52 for subject 4) -- fixed this to reflect the subject ID in the file name.

**Comment by egorananyev** [comment]
Obviously, please make sure that there are no 2's in the output for familiarity, congruence, etc. Please replace them with zeros at the output stage. I fixed this in the output for the four current subjects.

**Comment by PK-HQ** [comment]
Coding removal of 2s, Trial_number sequence, SubID column index, eyedom, thrlow+thrhigh+thrmean, column labels
