### ISSUE TITLE
Main: Increase effectiveness of attentional cueing

### ISSUE THREAD

**Issue by egorananyev** [PK-HQ/fc#5]
1. Increase white dot trials to 10% of total trials.
2. Present it for only 1s at full contrast at three different locations (left/center/right) and onset times (0.5, 1, 1.5) during the trial.
3. Combine this with an instruction - there will be a bonus for the expt, and it depends on how many you catch. Catch % of >80% will be rewarded in an incremental basis.
4. Present the sentences and the dots closer to the fixation.
5. Have participants indicate the location right away, without the space bar press, then go to the 'Press space bar for next trial' screen right away.

**Comment by PK-HQ** [comment]
Done 1, 3, 4
Ignoring 5
Coding lateral random location of 2, code dot timing (0.5-2s)

**Comment by PK-HQ** [comment]
Coding dot timing (0.5-2s)
